### ISSUE TITLE
Luckperms errors on start

### ISSUE THREAD

**Issue by Moose1301** [lucko/LuckPerms#2813]
### Description

When luckperms loaded it throws a NoSuchMethodError for  com.google.common.cache.CacheBuilder.build

### Reproduction steps

1. idk why

### Expected behaviour

Idk it not error on start

### Environment details

* Server type/version: `Spigot` running version `1.7.10` git-Spigot-1.7.9-R0.2-208-ge0f2e95`???`
* LuckPerms version: `v5.2.76 (Legacy)`

https://gist.github.com/Moose1301/095098e7ec0d5b93a455a287233f0918

**Comment by powercasgamer** [comment]
LuckPerms legacy will only work on 1.7.10, you'll need to upgrade from 1.7.9 to 1.7.10

**Comment by Moose1301** [comment]
it is a 1.7.10 server it even tho it says "git-Spigot-1.7.9-R0.2-208-ge0f2e95"

**Comment by benwoo1110** [comment]
How do you know, sing all evidence you send is pointing to a 1.7.9 server version. Can you send your full startup log?

**Comment by Moose1301** [comment]
https://gist.github.com/Moose1301/ad1ae2ad029e9eaa397648bb93e313ba

**Comment by powercasgamer** [comment]
Can you download [this](https://ci.lucko.me/job/LuckPerms/1242/artifact/bukkit-legacy/build/libs/LuckPerms-Bukkit-Legacy-5.2.76.jar) version then restart your server?

**Comment by lucko** [comment]
Try deleting the `LuckPerms/libs/` folder then restarting your server.

**Comment by Moose1301** [comment]
> 
> 
> Try deleting the `LuckPerms/libs/` folder then restarting your server.

That fixed it ty
