### ISSUE TITLE
BungeeCord issue 

### ISSUE THREAD

**Issue by Krispin02** [lucko/LuckPerms#2099]
Getting this issue when using a 1.7.10 bungeecord. Is it possible to get a version of luckperms-bungee that will work with 1.7.10?

15:32:18 [WARNING] Exception encountered when loading plugin: LuckPerms
java.lang.NoClassDefFoundError: com/google/gson/internal/bind/TreeTypeAdapter
    at me.lucko.luckperms.lib.text.adapter.bungeecord.TextAdapter0.bind(TextAdapter.java:104)
    at me.lucko.luckperms.lib.text.adapter.bungeecord.TextAdapter0.<clinit>(TextAdapter.java:76)
    at me.lucko.luckperms.lib.text.adapter.bungeecord.TextAdapter.sendComponent(TextAdapter.java:71)
    at me.lucko.luckperms.lib.text.adapter.bungeecord.TextAdapter.sendComponent(TextAdapter.java:61)
    at me.lucko.luckperms.bungee.BungeeSenderFactory.sendMessage(BungeeSenderFactory.java:70)
    at me.lucko.luckperms.bungee.BungeeSenderFactory.sendMessage(BungeeSenderFactory.java:65)
    at me.lucko.luckperms.bungee.BungeeSenderFactory.sendMessage(BungeeSenderFactory.java:42)
    at me.lucko.luckperms.common.sender.AbstractSender.sendMessage(AbstractSender.java:85)
    at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.displayBanner(AbstractLuckPermsPlugin.java:368)
    at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:107)
    at me.lucko.luckperms.bungee.LPBungeeBootstrap.onEnable(LPBungeeBootstrap.java:125)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:184)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:189)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:119)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:22)
Caused by: java.lang.ClassNotFoundException: com.google.gson.internal.bind.TreeTypeAdapter
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 15 more

**Comment by Andre601** [comment]
Just use latest Travertine version.
It's a Bungee fork with 1.7 support.

Other than that is there no 1.7 version of LuckPerms

**Comment by lucko** [comment]
^

Just swap your 1.7 BungeeCord jar out for this.

https://papermc.io/downloads#Travertine
