### ISSUE TITLE
Typing '/lp' or any other /-command in console outputs a java error (no crash though)

### ISSUE THREAD

**Issue by Robby-** [lucko/LuckPerms#2229]
Typing `/lp` or any other non-LP command prefixed with a `/` in the console produces some java error output, but luckily no crash, the server keeps running.

Probably introduced by 642d14d003fc9295f4b7ecfb55a79348ab234a46 if I have to guess.

Output is as follows:
```
>/lp
[16:28:32] [Server thread/ERROR]: Could not pass event ServerCommandEvent to LuckPerms v5.0.139
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
        at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:438) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:407) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getCommandMap()Lorg/bukkit/command/CommandMap;
        at me.lucko.luckperms.bukkit.BukkitCommandExecutor.onConsoleCommand(BukkitCommandExecutor.java:116) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
        ... 8 more
[16:28:32] [Server thread/INFO]: Unknown command. Type "/help" for help.
```

Spigot 1.15.2
LuckPerms 5.0.139

**Comment by Laarryy** [comment]
Most plugins don't allow for a / but luckperms should. Have you updated to the latest version from luckperms.net?

**Comment by OmegaWeaponDev** [comment]
Just use the commands in console without the `/` and they will work as normal.

**Comment by lucko** [comment]
Thanks for reporting :)
