### ISSUE TITLE
GroupManager migration to LuckPerms Error

### ISSUE THREAD

**Issue by Sukram28** [lucko/LuckPerms#4203]
### Description

Using the latest version of GroupManger, LuckPerms and luckperms-migration-groupmanager.jar
Im Running Paper 1.21.1. Im trying to migrate (especally all users) to LuckPerms since GroupManager doesnt work in 1.12.4+.

I tried: with LuckPerms h2 and YAML settings and I tried the data simplified GroupManager configuration of https://gist.github.com/Sukram28/e80f81751d6868c03ec50f6d118e3809 (link also below)

Full Server log and Error: https://pastebin.com/ifJwCMxT

Error: 
```
java.lang.NoSuchMethodError: 'org.anjocaido.groupmanager.data.UserVariables org.anjocaido.groupmanager.data.User.getVariables()'
        at luckperms-migration-groupmanager.jar/me.lucko.luckperms.migration.MigrationGroupManager.lambda$runMigration$5(MigrationGroupManager.java:191) ~[luckperms-migration-groupmanager.jar:?]
```

### Reproduction Steps

Im running Paper 1.21.1-latest, Groupmanger - latest and LuckPerm -latest. I followed the instrucktions of https://luckperms.net/wiki/Migration

My groupmanager strucktur is simple: Some world unspesifc ranks and many unsers assigned with a rank. Default is the Rank User

### Expected Behaviour

It sould convert the files, but doesnt instead crashes

### Server Details

Paper version 1.21.1-81-master@13a2395

### LuckPerms Version

v5.5.22

### Logs and Configs

GroupManager Settings 
https://gist.github.com/Sukram28/e80f81751d6868c03ec50f6d118e3809

### Extra Details

Except of Essentails ViaVersion and Multiverse no other plugins where used

**Comment by benwoo1110** [comment]
Seems like the migration code for group manager needs to update. It's build for GourpManager v1, while you are using a newer v3.
