### ISSUE TITLE
4.0.41 breaks MySQL and MariaDB (NoSuchMethodError: com.zaxxer.hikari.HikariConfig.setInitializationFailTimeout(J)V)

### ISSUE THREAD

**Issue by BrainStone** [lucko/LuckPerms#600]
Some change from 4.0.40 to 4.0.41 (94b4e3d36613b89efc1fb7101a06132b4d6ffc16...9dd4f715262cd4b433dae94dbbf9557c5829a2d8) breaks MySQL and MariaDB, as I get this error on startup. Works fine on 4.0.4:

```
[12:43:47 ERROR]: Error occurred while enabling LuckPerms v4.0.41 (Is it up to date?)
java.lang.NoSuchMethodError: com.zaxxer.hikari.HikariConfig.setInitializationFailTimeout(J)V
    at me.lucko.luckperms.common.storage.dao.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:96) ~[?:?]
    at me.lucko.luckperms.common.storage.dao.sql.SqlDao.init(SqlDao.java:153) ~[?:?]
    at me.lucko.luckperms.common.storage.AbstractStorage.init(AbstractStorage.java:94) ~[?:?]
    at me.lucko.luckperms.common.storage.wrappings.PhasedStorage.init(PhasedStorage.java:82) ~[?:?]
    at me.lucko.luckperms.common.storage.wrappings.BufferedOutputStorage.init(BufferedOutputStorage.java:46) ~[?:?]
    at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:115) ~[?:?]
    at me.lucko.luckperms.bukkit.LPBukkitPlugin.enable(LPBukkitPlugin.java:214) ~[?:?]
    at me.lucko.luckperms.bukkit.LPBukkitPlugin.onEnable(LPBukkitPlugin.java:175) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Spigot-549c1fa-70cc382]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-549c1fa-70cc382]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [server.jar:git-Spigot-549c1fa-70cc382]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382) [server.jar:git-Spigot-549c1fa-70cc382]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [server.jar:git-Spigot-549c1fa-70cc382]
    at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206) [server.jar:git-Spigot-549c1fa-70cc382]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-549c1fa-70cc382]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by BrainStone** [comment]
My guess would be that you compile against HikariCP 2.7.3 (https://github.com/lucko/LuckPerms/blob/master/common/pom.xml#L107) while you download HikariCP 2.7.4 (https://github.com/lucko/LuckPerms/blob/master/common/src/main/java/me/lucko/luckperms/common/dependencies/Dependency.java#L80)

**Comment by lucko** [comment]
Another plugin on your server is packaging an outdated version of HikariCP.

**Comment by BrainStone** [comment]
If that's the case it's LogBlock. Will have a look at that.

**Comment by BrainStone** [comment]
Yes it is: https://github.com/LogBlock/LogBlock/pull/707

I guess I can try removing the shadowed in hikari

**Comment by BrainStone** [comment]
Custom-Build it is :/
